title: 418 I'm a teapod
email: 418@teapod.club
description: >-
  a chill 20 to 30 minutes chatting about life and web tech
baseurl: ""
url: "https://teapod.club"

collections:
  posts:
    permalink: /:slug

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path:            "admin/**/*"
    values:
      sitemap:         false
